const { chromium } = require(process.argv[2]);
const assert = require('node:assert/strict');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:8766');
  await page.getByRole('button', { name: '新增專案', exact: true }).first().click();
  await page.locator('#projectTopic').fill('介面驗證專案');
  await page.locator('#createProjectBtn').click();
  await page.locator('#dlgProject').waitFor({ state: 'hidden' });
  assert.match(await page.locator('#projectName').textContent(), /介面驗證專案/);
  await page.getByRole('button', { name: '專案', exact: true }).click();
  await page.locator('#importFiles').setInputFiles({ name: 'smoke.txt', mimeType: 'text/plain', buffer: Buffer.from('browser upload') });
  await page.locator('#fileTree').getByRole('button', { name: 'smoke.txt', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('filePreview').textContent === 'browser upload');
  await page.locator('#fileSearch').fill('missing');
  await page.getByText('找不到符合的檔案', { exact: true }).waitFor();
  await page.locator('#fileSearch').fill('');
  await page.screenshot({ path: path.join(__dirname, 'ui-files.png'), fullPage: true });
  await page.getByRole('button', { name: 'Agent', exact: true }).click();
  await page.reload();
  await page.getByText('已匯入 smoke.txt', { exact: true }).waitFor();
  await page.screenshot({ path: path.join(__dirname, 'ui-desktop.png'), fullPage: true });
  await page.locator('#undoBtn').click();
  await page.getByText('已復原本回合檔案變更。', { exact: true }).waitFor();
  await page.getByRole('button', { name: '專案', exact: true }).click();
  await page.waitForFunction(() => !Array.from(document.querySelectorAll('#fileTree button')).some(b => b.textContent === 'smoke.txt'));
  await page.getByRole('button', { name: 'Agent', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile page must not overflow horizontally');
  await page.screenshot({ path: path.join(__dirname, 'ui-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: '公司閘道', exact: true }).first().click();
  await page.locator('#gatewayEndpoint').fill('https://example.invalid/v1');
  await page.locator('#gatewayModel').fill('test-model');
  await page.locator('#saveGatewayBtn').click();
  await page.locator('#dlgGateway').waitFor({ state: 'hidden' });
  await page.locator('#chatMode').selectOption('ask');
  await page.waitForFunction(() => document.getElementById('chatModeHint').textContent.includes('只讀取'));
  await page.reload();
  await page.waitForFunction(() => document.getElementById('chatMode').value === 'ask');
  assert.equal(await page.locator('#undoBtn').isDisabled(), true);
  await page.locator('#chatMode').selectOption('plan');
  await page.waitForFunction(() => document.getElementById('chatModeHint').textContent.includes('計畫'));
  await page.locator('#chatMode').selectOption('general');
  await page.waitForFunction(() => document.getElementById('chatModeHint').textContent.includes('修改'));
  await page.locator('#searchSettingsBtn').click();
  await page.locator('#searchUrl').waitFor({state: 'visible'});
  await page.locator('#searchClose').click();
  assert.deepEqual(errors, []);
  console.log('UI SMOKE OK: create, upload, preview, search, reload history, undo, settings, mobile layout');
  await browser.close();
})().catch(error => { console.error(error); process.exitCode = 1; });
